name: 'Configuration Manager'
type: module
description: 'Allows administrators to import and export configuration changes.'
package: Core
# version: VERSION
configure: config.sync

# Information added by Drupal.org packaging script on 2023-07-05
version: '10.0.10'
project: 'drupal'
datestamp: 1688549787
