name: 'Testing config import'
type: profile
description: 'Tests install profiles in the config importer.'
# version: VERSION
hidden: true
install:
  - syslog
themes:
  - stark

# Information added by Drupal.org packaging script on 2023-07-05
version: '10.0.10'
project: 'drupal'
datestamp: 1688549787
