_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  announcements_feed: 0
  automated_cron: 0
  backup_migrate: 0
  basic_auth: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  charts: 0
  charts_blocks: 0
  charts_google: 0
  ckeditor5: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  csv_serialization: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  encrypt: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  firebase: 0
  geolocation: 0
  geolocation_leaflet: 0
  hal: 0
  help: 0
  history: 0
  image: 0
  jquery_ui: 0
  jquery_ui_autocomplete: 0
  jquery_ui_menu: 0
  key: 0
  link: 0
  mailsystem: 0
  menu_link_content: 0
  menu_ui: 0
  met_api: 0
  met_data_converter: 0
  met_feel_earthquake: 0
  met_niwa: 0
  met_service: 0
  met_spc: 0
  met_tk: 0
  met_warning: 0
  mysql: 0
  node: 0
  node_view_permissions: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  phpass: 0
  remote_image: 0
  rest: 0
  restui: 0
  search: 0
  sendgrid_api: 0
  sendgrid_mailer: 0
  serialization: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  textfield_counter: 0
  toolbar: 0
  tour: 0
  update: 0
  upload_replace: 0
  user: 0
  views_data_export: 0
  views_ui: 0
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  olivero: 0
  claro: 0
profile: standard
