_core:
  default_config_hash: '-y1W5TduFDylWCKd_XkEImUVxXq2k8ycQSC8CfCav40'
server_key: 'AAAAg0kF7Gc:APA91bG8yOIEviCy5jucUEXxEyUhzW6QwjeGHYO7V55mme1FF6GJyyE9MiTQf5YotcKjBkSyl-5S6uuBucMxuZDhuBe5dYOgLPrM4B_AnavIxYY7kTBrhlENoxWda6LvfhGr-8BJUQdr'
sender_id: '563865840743 '
